// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"

	"github.com/tabbed/pqtype"
)

type Movie struct {
	Movieid     int32
	Title       string
	Year        sql.NullInt32
	ImdbUrl     sql.NullString
	Reccomender sql.NullString
	Tags        pqtype.NullRawMessage
	ContentType string
}
