// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/tabbed/pqtype"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (movieId, title, reccomender, tags, content_type, image, description)
  VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
  movieid, title, description, reccomender, image, tags, content_type
`

type CreateMovieParams struct {
	Movieid     string
	Title       string
	Reccomender sql.NullString
	Tags        pqtype.NullRawMessage
	ContentType string
	Image       string
	Description string
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, createMovie,
		arg.Movieid,
		arg.Title,
		arg.Reccomender,
		arg.Tags,
		arg.ContentType,
		arg.Image,
		arg.Description,
	)
	var i Movie
	err := row.Scan(
		&i.Movieid,
		&i.Title,
		&i.Description,
		&i.Reccomender,
		&i.Image,
		&i.Tags,
		&i.ContentType,
	)
	return i, err
}

const getMovie = `-- name: GetMovie :one
SELECT
  movieid, title, description, reccomender, image, tags, content_type
FROM
  movies
WHERE
  movieId = $1
LIMIT 1
`

func (q *Queries) GetMovie(ctx context.Context, movieid string) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovie, movieid)
	var i Movie
	err := row.Scan(
		&i.Movieid,
		&i.Title,
		&i.Description,
		&i.Reccomender,
		&i.Image,
		&i.Tags,
		&i.ContentType,
	)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT
  movieid, title, description, reccomender, image, tags, content_type
FROM
  movies
`

func (q *Queries) ListMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.Movieid,
			&i.Title,
			&i.Description,
			&i.Reccomender,
			&i.Image,
			&i.Tags,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
